### ISSUE TITLE
Just outputs trying: password even for correct password

### ISSUE THREAD

**Issue by kaiec** [devio/mod0keecrack#1]
Hi Thorsten,

I need to recover a kdbx database with keyfile and therefore would like to use your nice program. Unfortunately it doesn't seem to work in my case. 

I created two test databases (Keepass 2.24, Windows 10, x64): [tests.zip](https://github.com/devio/mod0keecrack/files/397997/tests.zip)
One with a corresponding keyfile, one without. 
Both use as master keyword: test

mod0keecrack was created using VS 2015 community edition on the same computer.

If I run the following command:

`echo test | mod0keecrack.exe keecrack-test-nofile.kdbx`

I get the following output:

```
[*] using  db: keecrack-test-nofile.kdbx
[*] using key: keecrack-test-nofile.key
[*] kdbx header:
[-]    file magic:          9aa2d903
[-]    file identifier:     b54bfb67
[-]    file minor version:  0001
[-]    file major version:  0003
[*] kdbx headerentries:
[-]    END:                 0D0A0D0A
[-]    COMMENT:
[-]    CIPHERID:            31C1F2E6BF714350BE5805216AFC5AFF
[-]    COMPRESSIONFLAGS:    00000001
[-]    MASTERSEED:          9A133102F9D2994B0F31295B756E68B993B3AF933D324960555DC59EBAC4E8B7
[-]    TRANSFORMSEED:       B9A62883EB9211F5C5034A6EBF4CBD5326C7A069134E33F951B4EB67E16FC55A
[-]    TRANSFORMROUNDS:     0000000000001770
[-]    ENCRYPTIONIV:        03CAAFEB3D65C04212D3E59A3ED54679
[-]    PROTECTEDSTREAMKEY:  5CB0FDCCF8848A6AAF2809B0C4942F0E47DFFB5DA70F2CEED98BC9BDF1ED465B
[-]    STREAMSTARTBYTES:    01B2E965B5D6A0294F5B1142D38E0E84DB28B2C101FD1CDB2F5ED87ECAA4786D
[-]    INNERRANDOMSTREAMID: 00000002
[*] kdbx payload:
[-]    payload offset:      de
[-]    payload len:         660
[*] Not using keyfile
[*] kdbx crack:
[+] trying: test
```

So there is no indication that the correct password has been found. The same for the one with the keyfile.

Any ideas?

Cheers,

Kai

**Comment by dgrechka** [comment]
I experience the same.

Attached zip contains kdbx and key file to reproduce. master password is "qwerty"

The files were created with KeePassX 2.0.3 on Windows.

[test3.zip](https://github.com/devio/mod0keecrack/files/554273/test3.zip)

**Comment by nabokov-ef** [comment]
I have tried your files and can confirm -- the tool does not decrypt these databases. It looks strange.
Along with that my test databases are decrypted successfully. KeePass 2.36 for Windows.

**Comment by evgeni-nabokov** [comment]
After some investigation I have figured out why it is not working.
@kaiec `echo test |` adds an extra space to your password, so it becames "test ". Use `echo test|` or a password file.
@dgrechka mod0keecrack does not support keepass-created xml files with a key in it. It only supports an arbitrary file as a big key itself. I think it is not hard to add the support of xml files. When I have it done, I will share.

**Comment by william-mendes** [comment]
Same issue as @dgrechka, my key file is in XML. Any news on that? 🙏

**Comment by kaiec** [comment]
@nabokov-ef Thanks a lot!
